"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "XXXXXX")
ENCRYPTION_KEY = os.getenv("ENCRYPTION_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG")

# Django environment
DJANGO_ENV = os.getenv("DJANGO_ENV")

# ALOWED_HOSTS based on Django environment
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost").split(",")

# NEXT_API_SECRET_KEY
NEXT_API_SECRET_KEY = os.getenv("NEXT_API_SECRET_KEY")

# localhost or NGINX reverse proxy
HTTPS = os.getenv("HTTPS") == "True"
if HTTPS or DJANGO_ENV == "production":
    BACKEND_URL = os.getenv("HTTPS_BACKEND_URL")
    FRONTEND_URL = os.getenv("HTTPS_FRONTEND_URL")
else:
    BACKEND_URL = os.getenv("HTTP_BACKEND_URL")
    FRONTEND_URL = os.getenv("HTTP_FRONTEND_URL")

# Application definition

APP_NAME = os.getenv("APP_NAME")

INSTALLED_APPS = [
    "core_db",
    "auth_api",
    "corsheaders",
    "rest_framework",
    "social_django",
    "drf_spectacular",
    "phonenumber_field",
    # "phone_verify",
    "storages",
    "django_filters",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "server.middlewares.RestrictDirectApiMiddleware",
]

ROOT_URLCONF = "server.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "server.wsgi.application"

PYTHONUNBUFFERED = 1

# * Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.getenv("DB_ENGINE"),
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
    }
}


# * Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
    {
        "NAME": "server.validators.PasswordComplexityValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# * REST Framework Settings

# Never give comma after drf_spectacular.openapi.AutoSchema
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": ("drf_spectacular.openapi.AutoSchema"),
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
        "rest_framework.permissions.IsAdminUser",
    ),
    "DEFAULT_FILTER_BACKENDS": ("django_filters.rest_framework.DjangoFilterBackend",),
    "DEFAULT_THROTTLE_CLASSES": (),
    # "DEFAULT_THROTTLE_RATES": {
    #     "email_otp": "15/min",
    #     "email_verify": "15/min",
    #     "password_reset": "15/min",
    #     "phone_otp": "15/min",
    # },
    "ORDERING_PARAM": "ordering",
}

# * DRF Spectacular Settings

SPECTACULAR_SETTINGS = {
    "TITLE": "SESSION DJREST AUTH API",
    "DESCRIPTION": "API for Session Authentication Template",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SECURITY": [
        {
            "NEXT_API_SECRET_KEY": [],
            "SessionAuth": [],
            "CsrfToken": [],
        }
    ],
    "APPEND_COMPONENTS": {
        "securitySchemes": {
            "NEXT_API_SECRET_KEY": {
                "type": "apiKey",
                "in": "header",
                "name": "NEXT-X-API-KEY",
                "description": "NEXT JS Frontend API Key (required alongside Session)",
            },
            "SessionAuth": {
                "type": "apiKey",
                "in": "cookie",
                "name": "sessionid",
                "description": "Standard Django session cookie authentication.",
            },
            "CsrfToken": {
                "type": "apiKey",
                "in": "header",
                "name": "X-CSRFToken",
                "description": "Django CSRF token required for state-changing requests.",
            },
        }
    },
}

# * Redis

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{os.environ.get('REDIS_HOST')}:{os.environ.get('REDIS_PORT')}/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

# * Celery

CELERY_REDIS_HOST = os.getenv("REDIS_HOST", "redis")
CELERY_REDIS_PORT = os.getenv("REDIS_PORT", "6379")
CELERY_BROKER_URL = f"redis://{CELERY_REDIS_HOST}:{CELERY_REDIS_PORT}/2"
CELERY_RESULT_BACKEND = f"redis://{CELERY_REDIS_HOST}:{CELERY_REDIS_PORT}/2"
CELERY_RESULT_EXPIRES = 3600

CELERY_WORKER_CONCURRENCY = int(os.getenv("CELERY_WORKER_CONCURRENCY", "4"))
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_ACKS_LATE = True

CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]


# * Time to Live (TTL) in seconds

SESSION_COOKIE_TTL = 24 * 60 * 60 + 10  # 1 day and 10 seconds
CSRF_TOKEN_TTL = 24 * 60 * 60 + 10  # 1 day and 10 seconds
PRE_AUTH_OTP_TTL = 10 * 60  # 10 minutes
LINK_EXPIRY_TTL = 10 * 60  # 10 minutes
OTP_COOLDOWN_TTL = 60  # 1 minute
LINK_COOLDOWN_TTL = 60  # 1 minute
INVALID_OTP_COOLDOWN_TTL = 60  # 1 minute
TWILIO_OTP_COOLDOWN_TTL = 60  # 1 minute
DUMMY_COOLDOWN_TTL = 600  # 10 minutes
LOGIN_FAILURE_ATTEMPT_TTL = 60 * 60  # 1 hour

# * Session Settings

SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_AGE = SESSION_COOKIE_TTL  # 1 day and 10 seconds
SESSION_COOKIE_SAME_SITE = "Lax"
SESSION_COOKIE_SECURE = True  # Secure session cookies
SESSION_CACHE_ALIAS = "default"

# * CORS Settings

CORS_ALLOWED_ORIGINS = os.getenv("CORS_ALLOWED_ORIGINS", "http://localhost:3000").split(
    ","
)
CORS_ALLOW_CREDENTIALS = True

# * CSRF Settings

CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS", "http://localhost:3000").split(
    ","
)
CSRF_COOKIE_SECURE = True  # Ensures the CSRF cookie is sent only over HTTPS
CSRF_COOKIE_HTTPONLY = True  # Must be False since JavaScript needs to read the token
CSRF_COOKIE_SAMESITE = "Lax"  # Prevent cross-origin requests
CSRF_COOKIE_AGE = CSRF_TOKEN_TTL  # 1 day and 10 seconds

# * Security Settings
MAX_LOGIN_FAILURE_LIMIT = 5
MAX_OTP_FAILURE_LIMIT = 3
SECURE_PROXY_SSL_HEADER = (
    "HTTP_X_FORWARDED_PROTO",
    "https",
)  # Only if Nginx is reverse proxied

# * User Settings

AUTH_USER_MODEL = "core_db.User"

# * Amazon settings

AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_REGION_NAME = os.getenv("AWS_REGION_NAME")


# * Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Global Static URL
STATIC_URL = "static/"

# Static and Media files
if DJANGO_ENV == "development":
    STATIC_ROOT = "/app/static"
    MEDIA_URL = "media/"
    MEDIA_ROOT = "/app/media"
else:
    STATIC_ROOT = "/home/django/app/static"
    AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_S3_STORAGE_BUCKET_NAME")
    AWS_S3_REGION_NAME = AWS_REGION_NAME
    AWS_S3_ADDRESSING_STYLE = "virtual"
    AWS_S3_SIGNATURE_VERSION = "s3v4"

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "location": "real-estate",
                "querystring_auth": False,
            },
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
    MEDIA_URL = (
        f"https://{AWS_STORAGE_BUCKET_NAME}.s3.ap-south-1.amazonaws.com/real-estate/"
    )
    AWS_DEFAULT_ACL = None
    AWS_S3_FILE_OVERWRITE = False

DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024

# * Authentication backends (custom + social auths)
# If one fails the next one runs, therefore don't use ModelBackend in case of CustomAuthBackend

AUTHENTICATION_BACKENDS = (
    "social_core.backends.google.GoogleOAuth2",
    # "social_core.backends.apple.AppleIdAuth",
    "social_core.backends.microsoft.MicrosoftOAuth2",
    "social_core.backends.facebook.FacebookOAuth2",
    "social_core.backends.amazon.AmazonOAuth2",
    "social_core.backends.github.GithubOAuth2",
    "social_core.backends.linkedin.LinkedinOpenIdConnect",
    "server.backends.CustomAuthBackend",
    # "django.contrib.auth.backends.ModelBackend",
)

# * Pipelines

SOCIAL_AUTH_PIPELINE = (
    "social_core.pipeline.social_auth.social_details",
    "social_core.pipeline.social_auth.social_uid",
    "social_core.pipeline.social_auth.auth_allowed",
    "social_core.pipeline.social_auth.social_user",
    "auth_api.pipelines.login_or_signup",
    "auth_api.pipelines.enforce_email_verification",
    "auth_api.pipelines.create_custom_user",
    "auth_api.pipelines.update_user_details",
    "social_core.pipeline.social_auth.associate_user",
    "social_core.pipeline.social_auth.load_extra_data",
)

SOCIAL_AUTH_DISCONNECT_PIPELINE = (
    "social_core.pipeline.disconnect.allowed_to_disconnect",
    "social_core.pipeline.disconnect.get_entries",
    "social_core.pipeline.disconnect.revoke_tokens",
    "social_core.pipeline.disconnect.disconnect",
)

# * Social django global settings

HTTP_PROXY = os.getenv("SOCIAL_AUTH_HTTP_PROXY_IP")
HTTPS_PROXY = os.getenv("SOCIAL_AUTH_HTTPS_PROXY_IP")

SOCIAL_AUTH_USER_MODEL = "core_db.User"
SOCIAL_AUTH_REQUESTS_TIMEOUT = 15
SOCIAL_AUTH_IMMUTABLE_USER_FIELDS = ["email"]
SOCIAL_AUTH_PROTECTED_USER_FIELDS = ["username", "phone_number"]
SOCIAL_AUTH_FORCE_EMAIL_LOWERCASE = True
SOCIAL_AUTH_REDIRECT_IS_HTTPS = True

if DJANGO_ENV == "production" and HTTP_PROXY and HTTPS_PROXY:
    SOCIAL_AUTH_PROXIES = {
        "http": HTTP_PROXY,
        "https": HTTPS_PROXY,
    }
else:
    SOCIAL_AUTH_PROXIES = {}

SOCIAL_AUTH_REVOKE_TOKENS_ON_DISCONNECT = True

# * Social auth settings per provider

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.getenv("GOOGLE_CLIENT_ID")
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.getenv("GOOGLE_CLIENT_SECRET")
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = ["openid", "email", "profile"]
SOCIAL_AUTH_GOOGLE_OAUTH2_USE_UNIQUE_USER_ID = True

# SOCIAL_AUTH_APPLE_ID_CLIENT = os.getenv("APPLE_CLIENT_ID")
# SOCIAL_AUTH_APPLE_ID_TEAM = os.getenv("APPLE_TEAM_ID")
# SOCIAL_AUTH_APPLE_ID_KEY = os.getenv("APPLE_KEY_ID")
# SOCIAL_AUTH_APPLE_ID_SECRET = os.getenv("APPLE_PRIVATE_KEY")
# SOCIAL_AUTH_APPLE_ID_SCOPE = ["email", "name"]

SOCIAL_AUTH_MICROSOFT_GRAPH_KEY = os.getenv("MICROSOFT_CLIENT_ID")
SOCIAL_AUTH_MICROSOFT_GRAPH_SECRET = os.getenv("MICROSOFT_CLIENT_SECRET")
SOCIAL_AUTH_MICROSOFT_GRAPH_SCOPE = ["openid", "email", "profile", "User.Read"]
SOCIAL_AUTH_MICROSOFT_GRAPH_EXTRA_DATA = [
    ("xms_edov", "xms_edov"),
]

SOCIAL_AUTH_FACEBOOK_KEY = os.getenv("FACEBOOK_CLIENT_ID")
SOCIAL_AUTH_FACEBOOK_SECRET = os.getenv("FACEBOOK_CLIENT_SECRET")
SOCIAL_AUTH_FACEBOOK_SCOPE = ["email"]
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
    "fields": "id,name,email,picture.width(500).height(500)",
}

SOCIAL_AUTH_GITHUB_KEY = os.getenv("GITHUB_CLIENT_ID")
SOCIAL_AUTH_GITHUB_SECRET = os.getenv("GITHUB_CLIENT_SECRET")
SOCIAL_AUTH_GITHUB_SCOPE = ["user:email", "read:user"]
SOCIAL_AUTH_GITHUB_EXTRA_DATA = [
    ("emails", "emails"),
]

SOCIAL_AUTH_AMAZON_KEY = os.getenv("AMAZON_CLIENT_ID")
SOCIAL_AUTH_AMAZON_SECRET = os.getenv("AMAZON_CLIENT_SECRET")
SOCIAL_AUTH_AMAZON_SCOPE = ["profile"]

SOCIAL_AUTH_LINKEDIN_OPENIDCONNECT_KEY = os.getenv("LINKEDIN_CLIENT_ID")
SOCIAL_AUTH_LINKEDIN_OPENIDCONNECT_SECRET = os.getenv("LINKEDIN_CLIENT_SECRET")
SOCIAL_AUTH_LINKEDIN_OPENIDCONNECT_SCOPE = ["openid", "profile", "email"]

# * Recaptcha Settings

RECAPTCHA_PROJECT_ID = os.getenv("GCP_PROJECT_ID", "xxxxx")
RECAPTCHA_SITE_KEY_V2 = os.getenv("RECAPTCHA_SITE_KEY_V2")
RECAPTCHA_SITE_KEY_V3 = os.getenv("RECAPTCHA_SITE_KEY_V3")

# * Email Settings

CONTACT_EMAIL = os.getenv("CONTACT_EMAIL")

if DJANGO_ENV == "development":
    # * Console
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    # * SMTP
    # EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_USE_TLS = True
    EMAIL_HOST = "smtp.gmail.com"
    EMAIL_PORT = 587
    EMAIL_HOST_USER = os.getenv("SMTP_EMAIL_HOST_USER")
    EMAIL_HOST_PASSWORD = os.getenv("SMTP_EMAIL_HOST_PASSWORD")
    DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
else:
    # #* AWS SES
    EMAIL_BACKEND = "django_ses.SESBackend"
    AWS_SES_REGION_NAME = AWS_REGION_NAME
    AWS_SES_REGION_ENDPOINT = f"email.{AWS_SES_REGION_NAME}.amazonaws.com"
    DEFAULT_FROM_EMAIL = os.getenv("AWS_SES_EMAIL")
    SERVER_EMAIL = os.getenv("AWS_SES_EMAIL")

# * Twilio Settings

TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID")
TWILIO_AUTH_TOKEN = os.getenv("TWILIO_AUTH_TOKEN")
TWILIO_PHONE_NUMBER = os.getenv("TWILIO_PHONE_NUMBER")
TWILIO_VERIFY_SERVICE_SID = os.getenv("TWILIO_VERIFY_SERVICE_SID")

# * Logo

LOGO = "logos/codextralogo.png"

if MEDIA_URL.startswith("http"):
    LOGO_URL = f"{MEDIA_URL}{LOGO}"
else:
    backend = BACKEND_URL.rstrip("/")
    media_path = MEDIA_URL.lstrip("/")
    LOGO_URL = f"{backend}/{media_path}{LOGO}"

# * Monitoring

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "loggers": {
        "": {  # Root logger
            "level": "INFO",
            "handlers": ["console"],
        },
        "django": {  # Django-specific logger
            "level": "INFO",
            "handlers": ["console"],
            "propagate": False,
        },
        "botocore": {  # botocore logger (for S3/AWS interactions)
            "level": "WARNING",
            "handlers": ["console"],
            "propagate": False,
        },
        "boto3": {  # boto3 logger
            "level": "WARNING",
            "handlers": ["console"],
            "propagate": False,
        },
        "s3transfer": {  # s3transfer logger (used by boto3 for file transfers)
            "level": "WARNING",
            "handlers": ["console"],
            "propagate": False,
        },
    },
}
